export const placeholderMovies = [
  {
    id: 1,
    title: 'The Grand Budapest Hotel',
    year: 2014,
    rating: 8.1,
    genre: 'Comedy, Drama',
    poster: 'https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/nX5XotM9yprCKarRH4fzOq1VM1J.jpg',
    overview: 'The adventures of Gustave H, a legendary concierge at a famous European hotel between the wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend.',
    director: 'Wes Anderson',
    runtime: '1h 40m',
  },
  {
    id: 2,
    title: 'Inception',
    year: 2010,
    rating: 8.8,
    genre: 'Sci-Fi, Action',
    poster: 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    director: 'Christopher Nolan',
    runtime: '2h 28m',
  },
  {
    id: 3,
    title: 'Spirited Away',
    year: 2001,
    rating: 8.6,
    genre: 'Animation, Fantasy',
    poster: 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/bSXfU4dwZyBA1vMmXvejdRXBvuF.jpg',
    overview: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
    director: 'Hayao Miyazaki',
    runtime: '2h 5m',
  },
  {
    id: 4,
    title: 'The Shawshank Redemption',
    year: 1994,
    rating: 9.3,
    genre: 'Drama',
    poster: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
    overview: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    director: 'Frank Darabont',
    runtime: '2h 22m',
  },
  {
    id: 5,
    title: 'Amélie',
    year: 2001,
    rating: 8.3,
    genre: 'Romance, Comedy',
    poster: 'https://image.tmdb.org/t/p/w500/6iZ2yY3m57H2w35t1O59WlUaY8r.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/eSVvx8xys2NuFhl8fevXt41wX7v.jpg',
    overview: 'Amélie is an innocent and naive girl in Paris with her own sense of justice. She decides to help those around her and, along the way, discovers love.',
    director: 'Jean-Pierre Jeunet',
    runtime: '2h 2m',
  },
  {
    id: 6,
    title: 'Interstellar',
    year: 2014,
    rating: 8.6,
    genre: 'Sci-Fi, Drama',
    poster: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg',
    overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    director: 'Christopher Nolan',
    runtime: '2h 49m',
  },
];
