export const placeholderMovies = [
  {
    id: 101,
    title: 'Aftersun',
    year: 2022,
    rating: 7.7,
    genre: 'Drama',
    poster: 'https://image.tmdb.org/t/p/w500/vJ26vW4hXmRzY7eK1jY5vHn2H4X.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/4uB4Wk3qgKx9v2o0L6j5G9K1N0p.jpg',
    overview: 'Sophie reflects on the shared joy and private melancholy of a holiday she took with her father 20 years earlier. Memories real and imagined fill the gaps.',
    director: 'Charlotte Wells',
    runtime: '1h 42m',
    moods: ['sad', 'inspired', 'bored'],
    pacing: 'slow',
    obscurity: 'hidden_gems',
    tone: 'cozy'
  },
  {
    id: 102,
    title: 'In the Mood for Love',
    year: 2000,
    rating: 8.1,
    genre: 'Drama, Romance',
    poster: 'https://image.tmdb.org/t/p/w500/iVzjh8tZ6bCq8Mv5R9mK6PqW0yZ.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/3Wn2Gq0d6kG1e4y7mN5V4k8L0qW.jpg',
    overview: 'Two neighbors form a strong bond after suspecting their spouses of extramarital activities, keeping their own affection chaste.',
    director: 'Wong Kar-wai',
    runtime: '1h 38m',
    moods: ['romantic', 'sad', 'inspired'],
    pacing: 'slow',
    obscurity: 'hidden_gems',
    tone: 'cozy'
  },
  {
    id: 103,
    title: 'The Secret Life of Walter Mitty',
    year: 2013,
    rating: 7.3,
    genre: 'Adventure, Comedy, Drama',
    poster: 'https://image.tmdb.org/t/p/w500/xZ71P7u1P4Zk3g9m5K6N7v8O9Pq.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/7WsyChQLEftFiDOVTGkv3hFpywq.jpg',
    overview: 'When his job is threatened, Walter Mitty takes action in the real world embarking on a global journey that turns into an irreplaceable adventure.',
    director: 'Ben Stiller',
    runtime: '1h 54m',
    moods: ['adventurous', 'inspired', 'bored', 'happy'],
    pacing: 'brisk',
    obscurity: 'mainstream',
    tone: 'cozy'
  },
  {
    id: 104,
    title: 'Drive My Car',
    year: 2021,
    rating: 7.9,
    genre: 'Drama',
    poster: 'https://image.tmdb.org/t/p/w500/7p7338O17476qYq1K69M5P1n5O3.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/6xYq2N4m9O4W7j5G9K1N0p9K1N0.jpg',
    overview: 'An aging, widowed theater director engages a taciturn young woman to be his chauffeur during a festival in Hiroshima, sparking quiet healing.',
    director: 'Ryusuke Hamaguchi',
    runtime: '2h 59m',
    moods: ['sad', 'inspired', 'bored'],
    pacing: 'slow',
    obscurity: 'hidden_gems',
    tone: 'mind-bending'
  },
  {
    id: 105,
    title: 'Living in Bondage: Breaking Free',
    year: 2019,
    rating: 7.1,
    genre: 'Drama, Mystery, Thriller',
    poster: 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?q=80&w=500&auto=format&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=1200&auto=format&fit=crop',
    overview: 'Nnamdi\'s secret quest for wealth and power draws him into a dark brotherhood, unlocking supernatural consequences in Lagos.',
    director: 'Ramsey Nouah',
    runtime: '2h 29m',
    moods: ['scared', 'adventurous', 'bored'],
    pacing: 'brisk',
    obscurity: 'hidden_gems',
    tone: 'dark'
  },
  {
    id: 106,
    title: 'Portrait of a Lady on Fire',
    year: 2019,
    rating: 8.1,
    genre: 'Drama, Romance',
    poster: 'https://image.tmdb.org/t/p/w500/2Lqa154ZSpT3OiN2wXN3802yibz.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/jB0h9X9Xn9K6j5G9K1N0p9K1N0p.jpg',
    overview: 'On an isolated island in Brittany at the end of the eighteenth century, a female painter is obliged to paint a wedding portrait of a young woman.',
    director: 'Céline Sciamma',
    runtime: '2h 2m',
    moods: ['romantic', 'sad', 'inspired'],
    pacing: 'slow',
    obscurity: 'hidden_gems',
    tone: 'cozy'
  },
  {
    id: 107,
    title: 'Everything Everywhere All at Once',
    year: 2022,
    rating: 8.8,
    genre: 'Action, Adventure, Sci-Fi',
    poster: 'https://image.tmdb.org/t/p/w500/r2JIG1XGZ42xT3jWz6K4mP38vO2.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/fw02ONlD2BkeA626XW5W42yibz.jpg',
    overview: 'An aging Chinese immigrant is swept up in an insane adventure where she alone can save the world by exploring other universes.',
    director: 'Daniel Kwan, Daniel Scheinert',
    runtime: '2h 19m',
    moods: ['happy', 'inspired', 'adventurous', 'bored'],
    pacing: 'brisk',
    obscurity: 'mainstream',
    tone: 'mind-bending'
  },
  {
    id: 108,
    title: 'Arrival',
    year: 2016,
    rating: 7.9,
    genre: 'Sci-Fi, Mystery',
    poster: 'https://image.tmdb.org/t/p/w500/x2LSRK2Cm7MZhjluni1msVJ3wDF.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/y4aD9K2m9O4W7j5G9K1N0p9K1N0.jpg',
    overview: 'A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.',
    director: 'Denis Villeneuve',
    runtime: '1h 56m',
    moods: ['inspired', 'stressed', 'bored'],
    pacing: 'slow',
    obscurity: 'mainstream',
    tone: 'mind-bending'
  },
  {
    id: 109,
    title: 'Perfect Days',
    year: 2023,
    rating: 7.9,
    genre: 'Drama',
    poster: 'https://image.tmdb.org/t/p/w500/7aZ1Y9m5K6N7v8O9PqXZ71P7u1P.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/8aZ1Y9m5K6N7v8O9PqXZ71P7u1P.jpg',
    overview: 'Hirayama seems entirely content with his simple life as a cleaner of toilets in Tokyo. Outside of his structured routine, he enjoys music, books, and trees.',
    director: 'Wim Wenders',
    runtime: '2h 4m',
    moods: ['inspired', 'happy', 'stressed', 'bored'],
    pacing: 'slow',
    obscurity: 'hidden_gems',
    tone: 'cozy'
  },
  {
    id: 110,
    title: 'The Worst Person in the World',
    year: 2021,
    rating: 7.8,
    genre: 'Comedy, Drama, Romance',
    poster: 'https://image.tmdb.org/t/p/w500/h6Y9m5K6N7v8O9PqXZ71P7u1P4Z.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/g6Y9m5K6N7v8O9PqXZ71P7u1P4Z.jpg',
    overview: 'Four years in the life of Julie, a young woman navigating the troubled waters of her love life and struggling to find her career path in Oslo.',
    director: 'Joachim Trier',
    runtime: '2h 8m',
    moods: ['romantic', 'inspired', 'sad', 'stressed'],
    pacing: 'brisk',
    obscurity: 'hidden_gems',
    tone: 'cozy'
  },
  {
    id: 111,
    title: 'Spider-Man: Into the Spider-Verse',
    year: 2018,
    rating: 8.4,
    genre: 'Animation, Action, Adventure',
    poster: 'https://image.tmdb.org/t/p/w500/iiZZdoQHeeBjh2WwYskUPvVGjW7.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/u2w1yZ1p7u1P4Zk3g9m5K6N7v8O.jpg',
    overview: 'Teen Miles Morales becomes the Spider-Man of his universe and must join with five spider-powered individuals from other dimensions.',
    director: 'Bob Persichetti, Peter Ramsey, Rodney Rothman',
    runtime: '1h 57m',
    moods: ['happy', 'adventurous', 'inspired', 'bored'],
    pacing: 'brisk',
    obscurity: 'mainstream',
    tone: 'cozy'
  },
  {
    id: 112,
    title: 'Pari',
    year: 2018,
    rating: 6.6,
    genre: 'Horror, Mystery',
    poster: 'https://image.tmdb.org/t/p/w500/9aZ1Y9m5K6N7v8O9PqXZ71P7u1P.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/0aZ1Y9m5K6N7v8O9PqXZ71P7u1P.jpg',
    overview: 'Arnab tries to help Ruksana, a chained woman found in a secluded hut, unaware that she is associated with a dark, demonic cult.',
    director: 'Prosit Roy',
    runtime: '2h 14m',
    moods: ['scared', 'stressed'],
    pacing: 'brisk',
    obscurity: 'hidden_gems',
    tone: 'dark'
  },
  {
    id: 113,
    title: 'Past Lives',
    year: 2023,
    rating: 7.9,
    genre: 'Drama, Romance',
    poster: 'https://image.tmdb.org/t/p/w500/k3Wfqn23hKz4v1y7mN5V4k8L0qW.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/l3Wfqn23hKz4v1y7mN5V4k8L0qW.jpg',
    overview: 'Nora and Hae Sung, two deeply connected childhood friends, are wrested apart after Nora\'s family emigrates from South Korea. Two decades later, they reunite for one fateful week.',
    director: 'Celine Song',
    runtime: '1h 46m',
    moods: ['romantic', 'sad', 'inspired'],
    pacing: 'slow',
    obscurity: 'hidden_gems',
    tone: 'cozy'
  },
  {
    id: 114,
    title: 'Get Out',
    year: 2017,
    rating: 7.7,
    genre: 'Horror, Mystery, Thriller',
    poster: 'https://image.tmdb.org/t/p/w500/t90YLnR2v2Y1jW2M9O4W7j5G9K1.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/u90YLnR2v2Y1jW2M9O4W7j5G9K1.jpg',
    overview: 'Chris, a young African-American man, visits his white girlfriend\'s family estate, where a disturbing series of discoveries leads him to an unthinkable truth.',
    director: 'Jordan Peele',
    runtime: '1h 44m',
    moods: ['scared', 'stressed', 'bored'],
    pacing: 'brisk',
    obscurity: 'mainstream',
    tone: 'dark'
  },
  {
    id: 115,
    title: 'Superbad',
    year: 2007,
    rating: 7.6,
    genre: 'Comedy',
    poster: 'https://image.tmdb.org/t/p/w500/ek8e8W24m9O4W7j5G9K1N0p9K1N.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/fk8e8W24m9O4W7j5G9K1N0p9K1N.jpg',
    overview: 'Two co-dependent high school seniors deal with separation anxiety after their plan to host a booze-soaked party goes awry.',
    director: 'Greg Mottola',
    runtime: '1h 53m',
    moods: ['happy', 'bored', 'stressed'],
    pacing: 'brisk',
    obscurity: 'mainstream',
    tone: 'cozy'
  }
];
